### ISSUE TITLE
Please modify the fractions in txdot cad export excel template

### ISSUE THREAD

**Issue by aminulce** [WSDOT/PGSuper#1]
Here is a screenshot for your reference

![Capture](https://github.com/WSDOT/PGSuper/assets/45325277/794fc0f8-054d-4f3b-9c49-04d1c3ad95c1)

**Comment by RickBrice** [comment]
Try installing the TxDOT fonts. See http://www.dot.state.tx.us/insdtdot/orgchart/cmd/cserve/standard/bridge-e.htm
